context:
  version: 0.2.0

package:
  name: cbfmt
  version: ${{ version }}

source:
  url: https://github.com/lukas-reineke/cbfmt/archive/v${{ version }}.tar.gz
  sha256: 42973e9b1e95f4f3d7e72ef17a41333dab1e04d3d91c7930aabfc08f72c14126

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cbfmt --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: A tool to format codeblocks inside markdown and org documents.
  homepage: https://github.com/lukas-reineke/cbfmt
  repository: https://github.com/lukas-reineke/cbfmt

extra:
  recipe-maintainers:
    - danielnachun
